name: Build and Push iTop Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'inventory.yml'
      - 'Dockerfile.template'
      - '.github/workflows/build-and-push.yml'
      - 'scripts/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker images
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh