name: Build and Push iTop Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Exécution hebdomadaire (dimanche à minuit)

permissions:
  contents: read
  packages: write  # Cette permission est nécessaire pour publier des images

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Dockerfile checksums
        uses: actions/cache@v3
        with:
          path: |
            .dockerfile_cache
            .known_images
          key: ${{ runner.os }}-dockerfile-cache-${{ hashFiles('inventory.yml', 'Dockerfile.template') }}
          restore-keys: |
            ${{ runner.os }}-dockerfile-cache-
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker images
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}